#!/usr/bin/env bash
# Assemble session context pack for AI — Context Operating System
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CTX="$ROOT/.factory/context"
MANIFEST="$CTX/CONTEXT_MANIFEST.json"
OUT="$CTX/SESSION_CONTEXT.md"

if [[ ! -f "$MANIFEST" ]]; then
  echo "HATA: CONTEXT_MANIFEST.json bulunamadı: $MANIFEST" >&2
  exit 1
fi

mkdir -p "$CTX"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Detect active phase from YAPILACAKLAR
PHASE=""
YAP="$ROOT/YAPILACAKLAR.md"
if [[ -f "$YAP" ]]; then
  PHASE="$(grep -E 'işleniyor' "$YAP" | head -1 | grep -oE 'F[0-8]' | head -1 || true)"
fi

{
  echo "# Session Context Pack"
  echo ""
  echo "| Generated | $NOW |"
  echo "| Active phase | ${PHASE:-unknown} |"
  echo ""
  echo "> Auto-generated by \`assemble-context.sh\`. Do not edit."
  echo ""
  echo "## Read order"
  echo ""
} > "$OUT"

python3 - "$ROOT" "$MANIFEST" "$OUT" "$PHASE" <<'PY'
import json
import sys
from pathlib import Path

root = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])
out_path = Path(sys.argv[3])
phase = sys.argv[4]

manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
lines = out_path.read_text(encoding="utf-8").splitlines()

def resolve(p: str) -> Path:
    return root / p

def exists(p: str) -> bool:
    return resolve(p).exists()

# Session start files
for item in manifest.get("session_start", []):
    path = item["path"]
    flag = "✅" if exists(path) else "⏭️ missing"
    lines.append(f"- [{flag}] `{path}` — {item.get('purpose', '')}")

# Phase overrides
if phase and phase in manifest.get("phase_overrides", {}):
    lines.append("")
    lines.append(f"## Phase {phase} additions")
    lines.append("")
    for p in manifest["phase_overrides"][phase]:
        flag = "✅" if exists(p) else "⏭️ missing"
        lines.append(f"- [{flag}] `{p}`")

# Knowledge hooks
lines.append("")
lines.append("## Knowledge hooks")
lines.append("")
for p in manifest.get("knowledge_hooks", []):
    flag = "✅" if exists(p) else "⏭️ missing"
    lines.append(f"- [{flag}] `{p}`")

# LAST_DECISION excerpt
last = root / ".factory/context/LAST_DECISION.md"
if last.exists():
    lines.append("")
    lines.append("## Last decision (excerpt)")
    lines.append("")
    text = last.read_text(encoding="utf-8").strip().splitlines()[:25]
    lines.extend(text)

# Runtime query hints
lines.append("")
lines.append("## Runtime queries")
lines.append("")
for q in manifest.get("runtime_queries", []):
    lines.append(f"- `{q.get('script')}` — {q.get('when', '')}")
    if q.get("example"):
        lines.append(f"  - Example: `{q['example']}`")

out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"   ✅ {out_path.relative_to(root)}")
PY

echo "   Cursor: @.factory/context/SESSION_CONTEXT.md @YAPILACAKLAR.md"
